Добавил Dockerfile и docker-compose
bobrutskovav/homework_spring2 pull request #12
Opened 2019-05-13 19:28 UTC by bobrutskovav

2019-05-15 07:14 UTC, ydvorzhetskiy requested changes

2019-05-15 07:14 UTC, ydvorzhetskiy commented on Dockerfile
> +COPY /library.jar /opt
Ох, а не /terget/library.jar?

2019-05-15 07:14 UTC, ydvorzhetskiy commented on Dockerfile
> +COPY /library.jar /opt
Да. и jar называется по-другому.

У меня не копировалась(

2019-05-15 07:36 UTC, bobrutskovav commented on Dockerfile
> +COPY /library.jar /opt
Поправил пути

2019-05-15 09:55 UTC, ydvorzhetskiy requested changes

2019-05-15 09:55 UTC, ydvorzhetskiy commented on docker-compose.yml
> +    tty: true
ВОт тут нужно задать URL монги

2019-05-16 18:19 UTC, closed without merging

2019-05-16 18:19 UTC, bobrutskovav commented
close